### ISSUE TITLE
💂‍♀️ SPIKE: Sentry TLS version

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/staff-device-dhcp-server#218]
"Hi Ministry of Justice,
As you may have seen, Sentry is planning to [retire support for TLS 1.0 and 1.1](https://go.sentry.io/Nzc2LU1KTi01MDEAAAGG20aCfleWLUo5AoFpkqHSdbg1sJnprBqbYHAet-_BMEi9BVCJlXop1QaZGCT3Ei5fF7ch0ks=).
Our records show that your organization has some projects using TLS 1.0.
We encourage you to upgrade some of your systems to support TLS 1.2+. We know that in some situations, it may not be possible to switch to newer TLS versions, so alternatively, we ask that you update your Sentry SDK configuration to allow TLS 1.0 usage.
If you are using the domain [oXXX.ingest.sentry.io](http://oxxx.ingest.sentry.io/) in your Sentry SDK configuration, then you can update it to [oXXX.insecure.sentry.io](http://oxxx.insecure.sentry.io/) to continue using TLS 1.0.
If you have any questions, please feel free to reply directly to this email.
The Sentry Team"

**Comment by ASTRobinson** [comment]
Spike completed: our systems support TLS 1.2+ so no further action is required.
