### ISSUE TITLE
⬆ Upgrade nginx version

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/staff-device-dhcp-server#229]
Alpine [version ](https://github.com/ministryofjustice/staff-device-dhcp-server/blob/b567cfeaa15d5d6930c1a7bad89c623269e5e034/nginx/Dockerfile)for nginx should be updated. This ought to be monitored in dependabot also. 

Latest version available [here](https://hub.docker.com/_/nginx).

**Comment by ASTRobinson** [comment]
alpine image updated to latest (raised by Dependabot) https://github.com/ministryofjustice/staff-device-dhcp-server/pull/252
