### ISSUE TITLE
🐛 aborted DB connections

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/staff-device-dhcp-server#232]
### Describe the bug.

Errors appearing in [/aws/rds/instance/staff-device-production-dhcp-db/error](https://eu-west-2.console.aws.amazon.com/cloudwatch/home?region=eu-west-2#logsV2:log-groups/log-group/$252Faws$252Frds$252Finstance$252Fstaff-device-production-dhcp-db$252Ferror) logs of the form: 

```
[Note] Aborted connection 33205 to db: 'staffdeviceproductiondhcp' user: 'dhcpuser' host: 'a.b.c.d' (Got an error reading communication packets)
```

### Environment

```markdown
- OS:
- Browser:
- Browser Version:
```

**Comment by tomwells98** [comment]
half a day max to be spent investigating
